// -*- mode: c++ -*-

#pragma once

#ifndef BUILD_INFORMATION
# define BUILD_INFORMATION "locally built"
#endif

#define KALEIDOSCOPE_HOSTOS_GUESSER 0

#define KALEIDOSCOPE_INCLUDE_TEST_MODE 0

#define KALEIDOSCOPE_INCLUDE_XCODE 1

#define KALEIDOSCOPE_INCLUDE_MORE_LED_EFFECTS 0

