// -*- mode: c++ -*-

#pragma once

#ifndef BUILD_INFORMATION
# define BUILD_INFORMATION "locally built"
#endif

#define KALEIDOSCOPE_HOSTOS_GUESSER 0

#define KALEIDOSCOPE_INCLUDE_TEST_MODE 0

#define KALEIDOSCOPE_INCLUDE_LEADER 0

#define KALEIDOSCOPE_INCLUDE_QUKEYS 0

#define KALEIDOSCOPE_INCLUDE_EMOJI 0

#define KALEIDOSCOPE_INCLUDE_XCODE 0

#define KALEIDOSCOPE_INCLUDE_TIMEKEEPER 0

#define KALEIDOSCOPE_INCLUDE_MORE_LED_EFFECTS 0

#define KALEIDOSCOPE_INCLUDE_HEATMAP 0

